server:
  port: 7075
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AccountantDB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    properties:
      hibernate:
        id:
          uuid_generator: org.hibernate.id.UUIDGenerator
#  security:
#    user:
#     password: password
#     name: user
  mvc:
   path match:
     matching-strategy: ANT_PATH_MATCHER

  application:
    name: accountantProject
